name: Build and Push pytorch

on:
  workflow_dispatch:

env:
  PYTORCH_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./pytorch/Dockerfile
        push: true
        tags: hushon/pytorch:${{ env.PYTORCH_TAG }}
        build-args: |
          PYTORCH_TAG=${{ env.PYTORCH_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
